logging:
  file.name: ./log/backend.log
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:h2:file:./database/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    hikari:
      idle-timeout: 30000
      max-lifetime: 30000
    name: database
  jpa:
    open-in-view: false
    show-sql: false
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      hbm2ddl.auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
