
    create table Movie (
       id bigint generated by default as identity,
        releaseDate date not null,
        runtime bigint not null,
        title varchar(255) not null,
        primary key (id)
    );
