


    create table movie (
       id bigint generated by default as identity,
        release_date date not null,
        runtime bigint not null,
        title varchar(255) not null,
        primary key (id)
    );

    create table user (
       id bigint generated by default as identity,
        email varchar(60) not null,
        password varchar(255) not null,
        primary key (id)
    );

    alter table user 
       add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
